# src/inits/sources.cmake
set(INITS_SOURCES
    acml_st1.F
    CMB_EvaluatePowerSpectrum.C
    ffte4X.F
    ffte_st1.F
    GenerateRealization.C
    InitializePowerSpectrum.C
    Main.C
    mkl_st1.F
    nr_1d.F
    nr_2d.F
    ReadParameterFile.C
    select_fft.F90
    sgi_st1_fft64.F
    adjfft.F
    AutomaticSubgridGeneration.C
    cosmo_functions.F
    CosmologyReadParameters.C
    cray_x1_fft64.F
    eisenstein_power.C
    enzo_ranf.C
    enzo_seed.C
    FastFourierTransform.C
    FastFourierTransformPrepareComplex.C
    FastFourierTransformSGIMATH.C
    FCol.C
    fft66.F
    fft90.F90
    fourn.F
    GenerateField.C
    ibm_fft64.F
    ibm_st1_fft64.F
    InterpretCommandLine.C
    nr_3d.F
    nr_st1.F
    power_of_2.F
    prefort2.F
    psfunc.F
    qromo.F
    ran1.F
    ReadPowerSpectrumParameters.C
    make_field_kpreserving.F
    make_field.F
    rotate2d.F
    rotate3d.F
    s66_st1.F
    s90_st1.F
    SetParameterDefaults.C
    shift.F
    spline.F
    stop_all_cpus.F
    wall_clock.c
    wrapper1d.F
    wrapper2d.F
    wrapper3d.F
    XChunk_WriteField.C
    XChunk_WriteIntField.C
)
